99 padroes grasp
UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs pull request #107
Opened 2021-09-02 01:40 UTC by tsrrodrigues

## Issue 
Resolve #99 

## Descrição
Cria o documento de padrões de projetos GRASPs.

## Checklist:

- [ ] Documento padronizado
- [ ] Documento sem erros ortográficos
- [ ] Descrição e divisão de padrões coerentes com o projeto

2021-09-02 10:14 UTC, sergiosacj requested changes
Achei que ficou massa.

Primeiro ponto que tenho é que acredito que seria interessante colocar justificativa nos padrões que foram escolhidos também. Deixo isso a critério de vocês para decidir se vale a pena ou não.

O segundo ponto é em relação ao histórico de versão dos padrões de projeto adotados, a numeração é realmente aquela?

E seria legal colocar, em algum lugar do documento, a reunião que realizamos para discutir esses padrões, afinal foi nela que definimos o que seria utilizado. (Depois que esse ponto aqui for concluído podem pedir para eu olhar de novo o PR)

2021-09-02 11:36 UTC, emysdias requested changes
![image](https://user-images.githubusercontent.com/52640974/131836677-1e450be8-f818-430d-ba2a-53b6a386ddb0.png)
tirar esse enumeração aqui pq acho q os outros não tem. E concordo com os pontos do Sérgio

2021-09-04 01:49 UTC, emysdias approved these changes
Agora está top top 🏆

2021-09-04 02:16 UTC, sergiosacj approved these changes
Com certeza deu um trampo corrigir isso tudo, valeu demais gente!

2021-09-04 02:17 UTC, merged