Adiciona Política de contribuição
UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs pull request #43
Opened 2021-08-05 15:35 UTC by lboaventura25

## Issue 
Resolve #41 

## Descrição
Cria política de contribuição para os repositórios de desenvolvimento e de documentação.

## Problemas conhecidos:

## Como validar?
Leia o documento e veja se está bem descrito, e com fluxos que auxiliem na contibuição da aplicação.

2021-08-05 20:52 UTC, sergiosacj requested changes
Mais um detalhe, seria interessante colocar "\&emsp;\&emsp;" no começo de todos os parágrafos. Só para ter a indentação correta mesmo.

2021-08-05 20:52 UTC, sergiosacj commented on docs/seminario1/politica-contribuicao.md
> +    git commit -m "Adiciona estrutura inicial do documento de identidade visual"
Para deixar um histórico mais limpo, seria interesante colocarmos o número da issue em todos os commits. Assim, a gente garante uma maior rastreabilidade, como também víncula todas as ações à um determinado problema.

Sugiro então que fique do seguinte modo:
```
git commit -m "(#43) Adicionando politica de commits"
```

2021-08-05 20:52 UTC, sergiosacj commented on docs/seminario1/politica-contribuicao.md
> +    git commit -m "Cria model do usuário
O mesmo vale para esse trecho aqui.

É importante enfatizar também o uso dos parênteses na hashtag da issue, porque facilita na hora de realizar o rebase. Já que quando se realiza o "commit --amend" o git considera linhas que começam com "#" comentários.

2021-08-05 21:13 UTC, lboaventura25 commented on docs/seminario1/politica-contribuicao.md
> +    git commit -m "Adiciona estrutura inicial do documento de identidade visual"
Eu coloquei no a identação por conta do css, @sergiosacj . Pra você não está funcionando?

2021-08-05 21:30 UTC, sergiosacj commented on docs/seminario1/politica-contribuicao.md
> +    git commit -m "Adiciona estrutura inicial do documento de identidade visual"
Tinha olhado errado, rodei de novo e estava tudo certo. Aquilo que comentei vai ter que ser removido dos demais então.

2021-08-05 21:35 UTC, lboaventura25 commented on docs/seminario1/politica-contribuicao.md
> +    git commit -m "Adiciona estrutura inicial do documento de identidade visual"
Gostei da ideia commit

2021-08-06 00:06 UTC, sergiosacj commented on docs/seminario1/politica-contribuicao.md
> +    git commit -m "Cria model do usuário
@lboaventura25 ficou faltando esse outro commit aqui. Colocar ele no mesmo padrão.

2021-08-06 00:08 UTC, sergiosacj approved these changes
Valeu!

2021-08-06 00:08 UTC, lboaventura25 commented on docs/seminario1/politica-contribuicao.md
> +    git commit -m "Cria model do usuário
🙄

2021-08-06 00:09 UTC, lboaventura25 commented on docs/seminario1/politica-contribuicao.md
> +    git commit -m "Cria model do usuário
Perdão!

2021-08-06 00:10 UTC, ServidioEC approved these changes

2021-08-06 00:12 UTC, merged