Dagramas atividade
UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs pull request #67
Opened 2021-08-15 23:31 UTC by emysdias

## Issue 
Resolve #
#57 

## Descrição
Adição dos diagramas de atividade

## Checklist:
- [x] Fazer o documento.
- [x] Colocar diagramas corretos
- [x] Ver repositórios anteriores

## Como validar?
Entrando na branch e vendo se o documento e os diagramas fazem sentido

2021-08-16 00:46 UTC, sergiosacj requested changes
Essa losango era para estar branco mesmo?
![Captura de tela de 2021-08-15 21-44-55](https://user-images.githubusercontent.com/36544528/129497951-01eec92f-ea0e-4fee-81a1-8797595d322f.png)

2021-08-16 00:53 UTC, emysdias commented
> Essa losango era para estar branco mesmo?
> ![Captura de tela de 2021-08-15 21-44-55](https://user-images.githubusercontent.com/36544528/129497951-01eec92f-ea0e-4fee-81a1-8797595d322f.png)

Quando a opção pode ser mais de uma, ai fica em branco mesmo

2021-08-16 00:57 UTC, sergiosacj approved these changes
Tudo certo então!

2021-08-16 22:59 UTC, brendavsantos submitted a review, later dismissed
O cliente só poderá realizar o pagamento através de um garçom, ou seja, quando solicita a conta pelo aplicativo o garçom é notificado e vem até a mesa oferecer as formas de pagamento(não está mais no escopo do nosso produto) nos diagramas é citado como "Paga e notifica garçom", acho que seria válido mudar para só ir até "solicitar conta" ou algo do tipo. Tirando isso ficou show demais!

2021-08-17 22:30 UTC, ServidioEC approved these changes

2021-08-18 01:01 UTC, merged