Adiciona Diagrama de  Estados
UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs pull request #76
Opened 2021-08-17 23:05 UTC by lboaventura25

## Issue 
Resolve #60 

## Descrição
Adiciona Diagrama de  Estados
## Checklist:

- [ ] Checar se o documento está de acordo com o escopo do projeto
- [ ] Validar a formatação e padronização do documento

2021-08-18 01:30 UTC, emysdias requested changes
Acho q ta ótimo, só atualizem com a devel ai vai ter uma pasta de modelagem, coloquem o arquivo lá please

e ta apontando uns erros no terminal
![image](https://user-images.githubusercontent.com/52640974/129822119-100e6020-b42b-4c39-b458-1186977c7c9c.png)

2021-08-18 13:27 UTC, ServidioEC commented
> Acho q ta ótimo, só atualizem com a devel ai vai ter uma pasta de modelagem, coloquem o arquivo lá por favor
> 
> e ta erros incorretos sem terminal
> ![imagem](https://user-images.githubusercontent.com/52640974/129822119-100e6020-b42b-4c39-b458-1186977c7c9c.png)

2021-08-20 23:50 UTC, tsrrodrigues approved these changes
Muito bom o documento, achei completo e bem escrito!

2021-08-22 01:50 UTC, emysdias approved these changes
🏆

2021-08-22 01:51 UTC, merged