6 documento benchmarking
UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs pull request #9
Opened 2021-08-01 02:29 UTC by tsrrodrigues

## Issue 
Resolves #
#6 

## Description
Cria documento de benchmarking.

## Checklist:
- [x] Documento compara os concorrentes com o nosso produto

## How to validate?
Verificar os seguintes pontos:
- [ ] Documento compara bem os concorrentes com o nosso produto?
- [ ] Documento está bem padronizado
- [ ] Documento não possui erros de português

2021-08-02 01:48 UTC, emysdias requested changes
Acho q como foi votado, falta enumerar o documento
![image](https://user-images.githubusercontent.com/52640974/127793879-ee762b6d-82e3-4b5d-9dba-a810a6062e51.png)
colocar tipo # 1. Introdução e ir seguindo

2021-08-02 01:48 UTC, emysdias commented on docs/seminario1/benchmarking.md
> +Inicialmente foi pensado em quais os sistemas concorrentes à proposta idealizada pelo "Tá na mesa" já conhecidos pelos integrantes e foram acrescentados alguns outros através de pesquisas. Assim que
```suggestion
Inicialmente foi pensado em quais os sistemas concorrentes à proposta idealizada pelo "Tá Na Mesa" já conhecidos pelos integrantes e foram acrescentados alguns outros através de pesquisas. Assim que foram identificados, os integrantes responsáveis pelo estudo foram até os estabelecimentos indicados e realizaram a análise do fluxo dos sistemas propostos para realizar pedidos. 
```

2021-08-02 01:50 UTC, emysdias reviewed
De forma geral o documento ficou ótimo!!

2021-08-02 17:10 UTC, lboaventura25 commented
Muito massa a análise descrita no documento!
Resolvendo o ponto que a @emysdias colocou eu já aprovo o PR!

2021-08-03 15:18 UTC, tsrrodrigues commented on docs/seminario1/benchmarking.md
> +Inicialmente foi pensado em quais os sistemas concorrentes à proposta idealizada pelo "Tá na mesa" já conhecidos pelos integrantes e foram acrescentados alguns outros através de pesquisas. Assim que
Valeu pelo feedback, Emily. Corrigido.

2021-08-03 15:32 UTC, lboaventura25 approved these changes
Show de bola! Esse documento deu água na boca rsrs

2021-08-03 23:25 UTC, emysdias commented
brabooo 🏆

2021-08-03 23:25 UTC, emysdias approved these changes

2021-08-03 23:25 UTC, merged